### ISSUE TITLE
Give a nice error message if I use an accessor instead of with...()

### ISSUE THREAD

**Issue by jessitron** [atomist/cortex#1]
I wrote in my query:
`query.forRoot<Build>( new Build().on())`
intending to ask for the repo of the build.

I got an exception:
`Caused by: javax.script.ScriptException: TypeError: Cannot read property "nodeTags" from undefined in .atomist/handlers/event/FailedBuild.js at line number 90`
... lots of other exception ick...

What I was supposed to write is:

`query.forRoot<Build>( new BuildStub().withOn(new RepoStub())))`

Please make the accessor methods like Build.on() throw an informative exception like "If you are trying to build a query by example, use `withOn` to ask for the repo" IF the internal property is undefined. 
(Rod says that if we've set the property earlier in the program, we should be able to retrieve it; but if it's still undefined then this isn't a valid access and we can provide the informative exception in the generated code.)

**Comment by johnsonr** [comment]
Moved to `rug`
